packages:
  - services/*

injectWorkspacePackages: true

loglevel: debug

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@firebase/util'
  - '@swc/core'
  - core-js
  - core-js-pure
  - esbuild
  - farmhash
  - msgpackr-extract
  - protobufjs

syncInjectedDepsAfterScripts:
  - docker:build
  - docker:build-beta
  - docker:build:push
  - docker:build-beta:push
