-- Down migration for management database

DROP TABLE IF EXISTS audits CASCADE;
DROP TABLE IF EXISTS documents CASCADE;
DROP TABLE IF EXISTS locales CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS templates CASCADE;
DROP TABLE IF EXISTS campaigns CASCADE;
DROP TABLE IF EXISTS subscriptions CASCADE;
DROP TABLE IF EXISTS providers CASCADE;
DROP TABLE IF EXISTS project_api_keys CASCADE;
DROP TABLE IF EXISTS project_admins CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS admins CASCADE;
DROP TABLE IF EXISTS organizations CASCADE;

DROP FUNCTION IF EXISTS set_updated_at();
DROP EXTENSION IF EXISTS "uuid-ossp";
