/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/conversations": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * List conversations
         * @description Returns a paginated list of conversations for the given project.
         */
        get: operations["listConversations"]
        put?: never
        /**
         * Create a new conversation
         * @description Creates a new AI builder conversation for generating email templates.
         *     Each conversation tracks a single template through iterative refinement.
         */
        post: operations["createConversation"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/v1/conversations/{conversation_id}": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * Get a conversation
         * @description Returns a conversation with its messages and the latest template version.
         */
        get: operations["getConversation"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/v1/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * List messages in a conversation
         * @description Returns all messages in a conversation in chronological order.
         */
        get: operations["listMessages"]
        put?: never
        /**
         * Send a message and stream the AI response as SSE
         * @description Sends a message to the AI agent within a conversation. The agent processes
         *     the message along with any provided context (images, section selection,
         *     current template, variables) and streams the response as Server-Sent Events.
         *
         *     SSE event types:
         *     - message_created: Initial event with message_id and conversation_id
         *     - delta: Token chunk from the AI response
         *     - code_start: Code fence opened
         *     - code_delta: Token chunk inside a code fence
         *     - code_end: Code fence closed, version persisted
         *     - done: Stream complete, includes the assistant message
         *     - error: Error occurred during streaming
         */
        post: operations["sendMessage"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/v1/conversations/{conversation_id}/versions": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        /**
         * List template versions
         * @description Returns all template versions for a conversation in chronological order.
         */
        get: operations["listVersions"]
        put?: never
        post?: never
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
    "/v1/conversations/{conversation_id}/versions/{version_number}/restore": {
        parameters: {
            query?: never
            header?: never
            path?: never
            cookie?: never
        }
        get?: never
        put?: never
        /**
         * Restore a template version
         * @description Restores a previous template version by creating a new version with the
         *     same content. Does not delete history — appends a new entry.
         */
        post: operations["restoreVersion"]
        delete?: never
        options?: never
        head?: never
        patch?: never
        trace?: never
    }
}
export type webhooks = Record<string, never>
export interface components {
    schemas: {
        CreateConversationRequest: {
            /**
             * Format: uuid
             * @description Optional template ID to associate this conversation with
             */
            template_id?: string
            /** @description Optional title for the conversation */
            title?: string
        }
        Conversation: {
            /** Format: uuid */
            id: string
            /** Format: uuid */
            project_id: string
            /** Format: uuid */
            template_id?: string | null
            title?: string | null
            /** Format: date-time */
            created_at: string
            /** Format: date-time */
            updated_at: string
        }
        ConversationList: {
            data: components["schemas"]["Conversation"][]
            total: number
        }
        ConversationDetail: {
            conversation: components["schemas"]["Conversation"]
            messages: components["schemas"]["Message"][]
            current_version: components["schemas"]["TemplateVersion"]
        }
        SendMessageRequest: {
            /** @description The user's natural language message */
            message: string
            /**
             * @description Role of the sender. Defaults to "user". Use "system" for
             *     automated messages such as compile-error fix requests.
             * @default user
             * @enum {string}
             */
            role: "user" | "system"
            /**
             * @description Optional sub-type that qualifies the message role. For example
             *     "compile_error" for automatic compile-fix requests.
             */
            kind?: string | null
            context?: components["schemas"]["MessageContext"]
        }
        MessageContext: {
            /** @description Images to include as context for the AI agent */
            images?: components["schemas"]["ImageReference"][]
            /** @description A specific email section selected via the element inspector */
            section?: components["schemas"]["SectionReference"]
            /** @description The current template HTML/JSX source */
            current_template?: string | null
            /** @description Campaign variables available for use in the template */
            variables?: components["schemas"]["VariableGroup"][]
        }
        ImageReference: {
            /** @description Name or filename of the image */
            name: string
            /** @description AI-generated or user-provided description of the image */
            description?: string
            /**
             * Format: uri
             * @description Public URL of the image
             */
            url: string
        }
        SectionReference: {
            /** @description Label of the selected section */
            label: string
            /** @description HTML content of the selected section */
            html: string
        }
        VariableGroup: {
            /** @description Group name (e.g., "user", "order") */
            name: string
            variables: components["schemas"]["Variable"][]
        }
        Variable: {
            /** @description Variable key path (e.g., "user.name") */
            key: string
            /** @enum {string} */
            type: "string" | "number" | "boolean" | "object" | "array"
            /** @description Description of the variable */
            description?: string
            /** @description Example value for the variable */
            example?: string
        }
        Message: {
            /** Format: uuid */
            id: string
            /** Format: uuid */
            conversation_id: string
            /** @enum {string} */
            role: "user" | "assistant" | "system"
            /** @description Optional sub-type that qualifies the role, e.g. "compile_error". */
            kind?: string | null
            /** @description The message text content */
            content: string
            /** @description Context attached to user messages */
            context?: components["schemas"]["MessageContext"]
            /** Format: date-time */
            created_at: string
        }
        MessageList: {
            data: components["schemas"]["Message"][]
        }
        TemplateVersion: {
            /** Format: uuid */
            id: string
            /** Format: uuid */
            conversation_id: string
            /**
             * Format: uuid
             * @description The assistant message that produced this version
             */
            message_id?: string | null
            version_number: number
            /** @description The generated React Email JSX/HTML template source */
            template: string
            /**
             * @description Template format (always full source)
             * @enum {string}
             */
            format: "full"
            /** Format: date-time */
            created_at: string
        }
        VersionList: {
            data: components["schemas"]["TemplateVersion"][]
        }
        AgentResponse: {
            message: components["schemas"]["Message"]
            /** @description The new template version, if the agent produced one */
            version: components["schemas"]["TemplateVersion"]
        }
    }
    responses: never
    parameters: {
        /** @description The project ID (forwarded from the platform) */
        ProjectID: string
        ConversationID: string
    }
    requestBodies: never
    headers: never
    pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
    listConversations: {
        parameters: {
            query?: {
                /** @description Filter conversations by template ID */
                template_id?: string
                limit?: number
                offset?: number
            }
            header: {
                /** @description The project ID (forwarded from the platform) */
                "X-Project-ID": components["parameters"]["ProjectID"]
            }
            path?: never
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description List of conversations */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ConversationList"]
                }
            }
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    createConversation: {
        parameters: {
            query?: never
            header: {
                /** @description The project ID (forwarded from the platform) */
                "X-Project-ID": components["parameters"]["ProjectID"]
            }
            path?: never
            cookie?: never
        }
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"]
            }
        }
        responses: {
            /** @description Conversation created successfully */
            201: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["Conversation"]
                }
            }
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    getConversation: {
        parameters: {
            query?: never
            header: {
                /** @description The project ID (forwarded from the platform) */
                "X-Project-ID": components["parameters"]["ProjectID"]
            }
            path: {
                conversation_id: components["parameters"]["ConversationID"]
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Conversation details */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["ConversationDetail"]
                }
            }
            /** @description Conversation not found */
            404: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    listMessages: {
        parameters: {
            query?: never
            header: {
                /** @description The project ID (forwarded from the platform) */
                "X-Project-ID": components["parameters"]["ProjectID"]
            }
            path: {
                conversation_id: components["parameters"]["ConversationID"]
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description List of messages */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["MessageList"]
                }
            }
            /** @description Conversation not found */
            404: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    sendMessage: {
        parameters: {
            query?: never
            header: {
                /** @description The project ID (forwarded from the platform) */
                "X-Project-ID": components["parameters"]["ProjectID"]
            }
            path: {
                conversation_id: components["parameters"]["ConversationID"]
            }
            cookie?: never
        }
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"]
            }
        }
        responses: {
            /** @description SSE event stream */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "text/event-stream": string
                }
            }
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
            /** @description Conversation not found */
            404: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    listVersions: {
        parameters: {
            query?: never
            header: {
                /** @description The project ID (forwarded from the platform) */
                "X-Project-ID": components["parameters"]["ProjectID"]
            }
            path: {
                conversation_id: components["parameters"]["ConversationID"]
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description List of template versions */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["VersionList"]
                }
            }
            /** @description Conversation not found */
            404: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
    restoreVersion: {
        parameters: {
            query?: never
            header: {
                /** @description The project ID (forwarded from the platform) */
                "X-Project-ID": components["parameters"]["ProjectID"]
            }
            path: {
                conversation_id: components["parameters"]["ConversationID"]
                version_number: number
            }
            cookie?: never
        }
        requestBody?: never
        responses: {
            /** @description Version restored successfully */
            200: {
                headers: {
                    [name: string]: unknown
                }
                content: {
                    "application/json": components["schemas"]["TemplateVersion"]
                }
            }
            /** @description Conversation or version not found */
            404: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown
                }
                content?: never
            }
        }
    }
}
