// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	HttpBearerAuthScopes = "HttpBearerAuth.Scopes"
)

// Defines values for AdminRole.
const (
	AdminRoleAdmin  AdminRole = "admin"
	AdminRoleMember AdminRole = "member"
	AdminRoleOwner  AdminRole = "owner"
)

// Defines values for CampaignChannel.
const (
	CampaignChannelEmail CampaignChannel = "email"
	CampaignChannelPush  CampaignChannel = "push"
	CampaignChannelSms   CampaignChannel = "sms"
)

// Defines values for CampaignUserStatus.
const (
	Aborted   CampaignUserStatus = "aborted"
	Failed    CampaignUserStatus = "failed"
	Opened    CampaignUserStatus = "opened"
	Pending   CampaignUserStatus = "pending"
	Sent      CampaignUserStatus = "sent"
	Throttled CampaignUserStatus = "throttled"
)

// Defines values for CreateAdminRole.
const (
	CreateAdminRoleAdmin  CreateAdminRole = "admin"
	CreateAdminRoleMember CreateAdminRole = "member"
	CreateAdminRoleOwner  CreateAdminRole = "owner"
)

// Defines values for CreateCampaignChannel.
const (
	CreateCampaignChannelEmail CreateCampaignChannel = "email"
	CreateCampaignChannelPush  CreateCampaignChannel = "push"
	CreateCampaignChannelSms   CreateCampaignChannel = "sms"
)

// Defines values for ProviderGroup.
const (
	ProviderGroupEmail ProviderGroup = "email"
	ProviderGroupPush  ProviderGroup = "push"
	ProviderGroupSms   ProviderGroup = "sms"
)

// Defines values for ProviderRateInterval.
const (
	Day    ProviderRateInterval = "day"
	Hour   ProviderRateInterval = "hour"
	Minute ProviderRateInterval = "minute"
	Second ProviderRateInterval = "second"
)

// Defines values for TemplateType.
const (
	TemplateTypeEmail TemplateType = "email"
	TemplateTypePush  TemplateType = "push"
	TemplateTypeSms   TemplateType = "sms"
)

// Defines values for UpdateAdminRole.
const (
	UpdateAdminRoleAdmin  UpdateAdminRole = "admin"
	UpdateAdminRoleMember UpdateAdminRole = "member"
	UpdateAdminRoleOwner  UpdateAdminRole = "owner"
)

// Admin defines model for Admin.
type Admin struct {
	CreatedAt      time.Time           `json:"created_at"`
	Email          openapi_types.Email `json:"email"`
	ExternalId     *string             `json:"external_id,omitempty"`
	FirstName      *string             `json:"first_name,omitempty"`
	Id             openapi_types.UUID  `json:"id"`
	ImageUrl       *string             `json:"image_url,omitempty"`
	LastName       *string             `json:"last_name,omitempty"`
	OrganizationId openapi_types.UUID  `json:"organization_id"`
	Role           AdminRole           `json:"role"`
	UpdatedAt      time.Time           `json:"updated_at"`
}

// AdminRole defines model for Admin.Role.
type AdminRole string

// Campaign defines model for Campaign.
type Campaign struct {
	Channel        CampaignChannel     `json:"channel"`
	CreatedAt      time.Time           `json:"created_at"`
	Delivery       Delivery            `json:"delivery"`
	Id             openapi_types.UUID  `json:"id"`
	Name           string              `json:"name"`
	ProjectId      openapi_types.UUID  `json:"project_id"`
	Provider       *Provider           `json:"provider,omitempty"`
	SubscriptionId *openapi_types.UUID `json:"subscription_id,omitempty"`
	Templates      []Template          `json:"templates"`
	UpdatedAt      time.Time           `json:"updated_at"`
}

// CampaignChannel defines model for Campaign.Channel.
type CampaignChannel string

// CampaignUser defines model for CampaignUser.
type CampaignUser struct {
	CampaignId openapi_types.UUID `json:"campaign_id"`
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	SentAt     *time.Time         `json:"sent_at,omitempty"`
	Status     CampaignUserStatus `json:"status"`
	UpdatedAt  time.Time          `json:"updated_at"`
	UserId     openapi_types.UUID `json:"user_id"`
}

// CampaignUserStatus defines model for CampaignUser.Status.
type CampaignUserStatus string

// CreateAdmin defines model for CreateAdmin.
type CreateAdmin struct {
	Email     openapi_types.Email `json:"email"`
	FirstName *string             `json:"first_name,omitempty"`
	LastName  *string             `json:"last_name,omitempty"`
	Role      CreateAdminRole     `json:"role"`
}

// CreateAdminRole defines model for CreateAdmin.Role.
type CreateAdminRole string

// CreateCampaign defines model for CreateCampaign.
type CreateCampaign struct {
	Channel        CreateCampaignChannel `json:"channel"`
	Name           string                `json:"name"`
	ProviderId     *openapi_types.UUID   `json:"provider_id,omitempty"`
	SubscriptionId *openapi_types.UUID   `json:"subscription_id,omitempty"`
}

// CreateCampaignChannel defines model for CreateCampaign.Channel.
type CreateCampaignChannel string

// Delivery defines model for Delivery.
type Delivery struct {
	Clicks int `json:"clicks"`
	Opens  int `json:"opens"`
	Sent   int `json:"sent"`
	Total  int `json:"total"`
}

// EmailProviderData defines model for EmailProviderData.
type EmailProviderData struct {
	DefaultFrom       *string `json:"default_from,omitempty"`
	DefaultFromLocked *bool   `json:"default_from_locked,omitempty"`
	DefaultFromName   *string `json:"default_from_name,omitempty"`
}

// EmailTemplateData defines model for EmailTemplateData.
type EmailTemplateData struct {
	// Editor Editor configuration and content structure
	Editor *struct {
		Content *[]map[string]interface{} `json:"content,omitempty"`
		Root    *struct {
			Props *map[string]interface{} `json:"props,omitempty"`
		} `json:"root,omitempty"`
		Zones *map[string]interface{} `json:"zones,omitempty"`
	} `json:"editor,omitempty"`
	From *map[string]interface{} `json:"from,omitempty"`

	// Html HTML content of the email template
	Html    *string `json:"html,omitempty"`
	Subject *string `json:"subject,omitempty"`
}

// PaginatedResponse defines model for PaginatedResponse.
type PaginatedResponse struct {
	// Limit Maximum number of items returned
	Limit int `json:"limit"`

	// Offset Number of items skipped
	Offset int `json:"offset"`

	// Total Total number of items matching the filters
	Total int `json:"total"`
}

// Problem defines model for Problem.
type Problem struct {
	// Detail A human readable explanation specific to this occurrence of the problem that is helpful to locate the problem and give advice on how to proceed. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.
	Detail string `json:"detail"`

	// Title A short summary of the problem type. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.
	Title string `json:"title"`
}

// Provider defines model for Provider.
type Provider struct {
	CreatedAt    time.Time             `json:"created_at"`
	Data         *json.RawMessage      `json:"data,omitempty"`
	Group        ProviderGroup         `json:"group"`
	Id           openapi_types.UUID    `json:"id"`
	IsDefault    bool                  `json:"is_default"`
	Name         string                `json:"name"`
	ProjectId    openapi_types.UUID    `json:"project_id"`
	RateInterval *ProviderRateInterval `json:"rate_interval,omitempty"`
	RateLimit    *int32                `json:"rate_limit,omitempty"`
	Type         string                `json:"type"`
	UpdatedAt    time.Time             `json:"updated_at"`
}

// ProviderGroup defines model for Provider.Group.
type ProviderGroup string

// ProviderRateInterval defines model for Provider.RateInterval.
type ProviderRateInterval string

// PushProviderData defines model for PushProviderData.
type PushProviderData = map[string]interface{}

// PushTemplateData defines model for PushTemplateData.
type PushTemplateData struct {
	// Body Push notification body
	Body *string `json:"body,omitempty"`

	// Data Additional data payload for the push notification
	Data *map[string]interface{} `json:"data,omitempty"`

	// Title Push notification title
	Title *string `json:"title,omitempty"`
}

// SmsProviderData defines model for SmsProviderData.
type SmsProviderData = map[string]interface{}

// SmsTemplateData defines model for SmsTemplateData.
type SmsTemplateData struct {
	// Body SMS message body
	Body *string `json:"body,omitempty"`
}

// Template defines model for Template.
type Template struct {
	CampaignId openapi_types.UUID `json:"campaign_id"`
	CreatedAt  time.Time          `json:"created_at"`
	Data       json.RawMessage    `json:"data"`
	Id         openapi_types.UUID `json:"id"`
	Locale     string             `json:"locale"`
	ProjectId  openapi_types.UUID `json:"project_id"`
	Type       TemplateType       `json:"type"`
	UpdatedAt  time.Time          `json:"updated_at"`
}

// TemplateType defines model for Template.Type.
type TemplateType string

// UpdateAdmin defines model for UpdateAdmin.
type UpdateAdmin struct {
	Email     *openapi_types.Email `json:"email,omitempty"`
	FirstName *string              `json:"first_name,omitempty"`
	LastName  *string              `json:"last_name,omitempty"`
	Role      *UpdateAdminRole     `json:"role,omitempty"`
}

// UpdateAdminRole defines model for UpdateAdmin.Role.
type UpdateAdminRole string

// UpdateCampaign defines model for UpdateCampaign.
type UpdateCampaign struct {
	Name       *string             `json:"name,omitempty"`
	ProviderId *openapi_types.UUID `json:"provider_id,omitempty"`
}

// Limit defines model for Limit.
type Limit = PaginationLimit

// Offset defines model for Offset.
type Offset = PaginationOffset

// CampaignListResponse defines model for CampaignListResponse.
type CampaignListResponse struct {
	// Limit Maximum number of items returned
	Limit int `json:"limit"`

	// Offset Number of items skipped
	Offset  int        `json:"offset"`
	Results []Campaign `json:"results"`

	// Total Total number of items matching the filters
	Total int `json:"total"`
}

// Error defines model for Error.
type Error = Problem

// ListAdminsParams defines parameters for ListAdmins.
type ListAdminsParams struct {
	// Limit Maximum number of items to return
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Search Search query to filter admins by name or email
	Search *string `form:"search,omitempty" json:"search,omitempty"`
}

// ListCampaignsParams defines parameters for ListCampaigns.
type ListCampaignsParams struct {
	// Limit Maximum number of items to return
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetCampaignUsersParams defines parameters for GetCampaignUsers.
type GetCampaignUsersParams struct {
	// Limit Maximum number of items to return
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateAdminJSONRequestBody defines body for CreateAdmin for application/json ContentType.
type CreateAdminJSONRequestBody = CreateAdmin

// UpdateAdminJSONRequestBody defines body for UpdateAdmin for application/json ContentType.
type UpdateAdminJSONRequestBody = UpdateAdmin

// CreateCampaignJSONRequestBody defines body for CreateCampaign for application/json ContentType.
type CreateCampaignJSONRequestBody = CreateCampaign

// UpdateCampaignJSONRequestBody defines body for UpdateCampaign for application/json ContentType.
type UpdateCampaignJSONRequestBody = UpdateCampaign

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListAdmins request
	ListAdmins(ctx context.Context, params *ListAdminsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateAdminWithBody request with any body
	CreateAdminWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateAdmin(ctx context.Context, body CreateAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteAdmin request
	DeleteAdmin(ctx context.Context, adminID openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAdmin request
	GetAdmin(ctx context.Context, adminID openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateAdminWithBody request with any body
	UpdateAdminWithBody(ctx context.Context, adminID openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateAdmin(ctx context.Context, adminID openapi_types.UUID, body UpdateAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProfile request
	GetProfile(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListCampaigns request
	ListCampaigns(ctx context.Context, projectID openapi_types.UUID, params *ListCampaignsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateCampaignWithBody request with any body
	CreateCampaignWithBody(ctx context.Context, projectID openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateCampaign(ctx context.Context, projectID openapi_types.UUID, body CreateCampaignJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteCampaign request
	DeleteCampaign(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCampaign request
	GetCampaign(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateCampaignWithBody request with any body
	UpdateCampaignWithBody(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateCampaign(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, body UpdateCampaignJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DuplicateCampaign request
	DuplicateCampaign(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCampaignUsers request
	GetCampaignUsers(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, params *GetCampaignUsersParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListAdmins(ctx context.Context, params *ListAdminsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListAdminsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateAdminWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAdminRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateAdmin(ctx context.Context, body CreateAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAdminRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteAdmin(ctx context.Context, adminID openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAdminRequest(c.Server, adminID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAdmin(ctx context.Context, adminID openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAdminRequest(c.Server, adminID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateAdminWithBody(ctx context.Context, adminID openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateAdminRequestWithBody(c.Server, adminID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateAdmin(ctx context.Context, adminID openapi_types.UUID, body UpdateAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateAdminRequest(c.Server, adminID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProfile(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProfileRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListCampaigns(ctx context.Context, projectID openapi_types.UUID, params *ListCampaignsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCampaignsRequest(c.Server, projectID, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateCampaignWithBody(ctx context.Context, projectID openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCampaignRequestWithBody(c.Server, projectID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateCampaign(ctx context.Context, projectID openapi_types.UUID, body CreateCampaignJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCampaignRequest(c.Server, projectID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteCampaign(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteCampaignRequest(c.Server, projectID, campaignID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCampaign(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCampaignRequest(c.Server, projectID, campaignID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateCampaignWithBody(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateCampaignRequestWithBody(c.Server, projectID, campaignID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateCampaign(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, body UpdateCampaignJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateCampaignRequest(c.Server, projectID, campaignID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DuplicateCampaign(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDuplicateCampaignRequest(c.Server, projectID, campaignID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCampaignUsers(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, params *GetCampaignUsersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCampaignUsersRequest(c.Server, projectID, campaignID, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListAdminsRequest generates requests for ListAdmins
func NewListAdminsRequest(server string, params *ListAdminsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/admin/organizations/admins")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Search != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "search", runtime.ParamLocationQuery, *params.Search); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateAdminRequest calls the generic CreateAdmin builder with application/json body
func NewCreateAdminRequest(server string, body CreateAdminJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateAdminRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateAdminRequestWithBody generates requests for CreateAdmin with any type of body
func NewCreateAdminRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/admin/organizations/admins")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteAdminRequest generates requests for DeleteAdmin
func NewDeleteAdminRequest(server string, adminID openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "adminID", runtime.ParamLocationPath, adminID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/admin/organizations/admins/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAdminRequest generates requests for GetAdmin
func NewGetAdminRequest(server string, adminID openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "adminID", runtime.ParamLocationPath, adminID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/admin/organizations/admins/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateAdminRequest calls the generic UpdateAdmin builder with application/json body
func NewUpdateAdminRequest(server string, adminID openapi_types.UUID, body UpdateAdminJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateAdminRequestWithBody(server, adminID, "application/json", bodyReader)
}

// NewUpdateAdminRequestWithBody generates requests for UpdateAdmin with any type of body
func NewUpdateAdminRequestWithBody(server string, adminID openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "adminID", runtime.ParamLocationPath, adminID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/admin/organizations/admins/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetProfileRequest generates requests for GetProfile
func NewGetProfileRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/admin/profile")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListCampaignsRequest generates requests for ListCampaigns
func NewListCampaignsRequest(server string, projectID openapi_types.UUID, params *ListCampaignsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectID", runtime.ParamLocationPath, projectID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/admin/projects/%s/campaigns", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateCampaignRequest calls the generic CreateCampaign builder with application/json body
func NewCreateCampaignRequest(server string, projectID openapi_types.UUID, body CreateCampaignJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateCampaignRequestWithBody(server, projectID, "application/json", bodyReader)
}

// NewCreateCampaignRequestWithBody generates requests for CreateCampaign with any type of body
func NewCreateCampaignRequestWithBody(server string, projectID openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectID", runtime.ParamLocationPath, projectID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/admin/projects/%s/campaigns", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteCampaignRequest generates requests for DeleteCampaign
func NewDeleteCampaignRequest(server string, projectID openapi_types.UUID, campaignID openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectID", runtime.ParamLocationPath, projectID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "campaignID", runtime.ParamLocationPath, campaignID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/admin/projects/%s/campaigns/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCampaignRequest generates requests for GetCampaign
func NewGetCampaignRequest(server string, projectID openapi_types.UUID, campaignID openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectID", runtime.ParamLocationPath, projectID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "campaignID", runtime.ParamLocationPath, campaignID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/admin/projects/%s/campaigns/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateCampaignRequest calls the generic UpdateCampaign builder with application/json body
func NewUpdateCampaignRequest(server string, projectID openapi_types.UUID, campaignID openapi_types.UUID, body UpdateCampaignJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateCampaignRequestWithBody(server, projectID, campaignID, "application/json", bodyReader)
}

// NewUpdateCampaignRequestWithBody generates requests for UpdateCampaign with any type of body
func NewUpdateCampaignRequestWithBody(server string, projectID openapi_types.UUID, campaignID openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectID", runtime.ParamLocationPath, projectID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "campaignID", runtime.ParamLocationPath, campaignID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/admin/projects/%s/campaigns/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDuplicateCampaignRequest generates requests for DuplicateCampaign
func NewDuplicateCampaignRequest(server string, projectID openapi_types.UUID, campaignID openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectID", runtime.ParamLocationPath, projectID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "campaignID", runtime.ParamLocationPath, campaignID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/admin/projects/%s/campaigns/%s/duplicate", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCampaignUsersRequest generates requests for GetCampaignUsers
func NewGetCampaignUsersRequest(server string, projectID openapi_types.UUID, campaignID openapi_types.UUID, params *GetCampaignUsersParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "projectID", runtime.ParamLocationPath, projectID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "campaignID", runtime.ParamLocationPath, campaignID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/admin/projects/%s/campaigns/%s/users", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "offset", runtime.ParamLocationQuery, *params.Offset); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListAdminsWithResponse request
	ListAdminsWithResponse(ctx context.Context, params *ListAdminsParams, reqEditors ...RequestEditorFn) (*ListAdminsResponse, error)

	// CreateAdminWithBodyWithResponse request with any body
	CreateAdminWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAdminResponse, error)

	CreateAdminWithResponse(ctx context.Context, body CreateAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAdminResponse, error)

	// DeleteAdminWithResponse request
	DeleteAdminWithResponse(ctx context.Context, adminID openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteAdminResponse, error)

	// GetAdminWithResponse request
	GetAdminWithResponse(ctx context.Context, adminID openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetAdminResponse, error)

	// UpdateAdminWithBodyWithResponse request with any body
	UpdateAdminWithBodyWithResponse(ctx context.Context, adminID openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateAdminResponse, error)

	UpdateAdminWithResponse(ctx context.Context, adminID openapi_types.UUID, body UpdateAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateAdminResponse, error)

	// GetProfileWithResponse request
	GetProfileWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetProfileResponse, error)

	// ListCampaignsWithResponse request
	ListCampaignsWithResponse(ctx context.Context, projectID openapi_types.UUID, params *ListCampaignsParams, reqEditors ...RequestEditorFn) (*ListCampaignsResponse, error)

	// CreateCampaignWithBodyWithResponse request with any body
	CreateCampaignWithBodyWithResponse(ctx context.Context, projectID openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCampaignResponse, error)

	CreateCampaignWithResponse(ctx context.Context, projectID openapi_types.UUID, body CreateCampaignJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCampaignResponse, error)

	// DeleteCampaignWithResponse request
	DeleteCampaignWithResponse(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteCampaignResponse, error)

	// GetCampaignWithResponse request
	GetCampaignWithResponse(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetCampaignResponse, error)

	// UpdateCampaignWithBodyWithResponse request with any body
	UpdateCampaignWithBodyWithResponse(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateCampaignResponse, error)

	UpdateCampaignWithResponse(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, body UpdateCampaignJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateCampaignResponse, error)

	// DuplicateCampaignWithResponse request
	DuplicateCampaignWithResponse(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, reqEditors ...RequestEditorFn) (*DuplicateCampaignResponse, error)

	// GetCampaignUsersWithResponse request
	GetCampaignUsersWithResponse(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, params *GetCampaignUsersParams, reqEditors ...RequestEditorFn) (*GetCampaignUsersResponse, error)
}

type ListAdminsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		// Limit Maximum number of items returned
		Limit int `json:"limit"`

		// Offset Number of items skipped
		Offset  int     `json:"offset"`
		Results []Admin `json:"results"`

		// Total Total number of items matching the filters
		Total int `json:"total"`
	}
	JSONDefault *Error
}

// Status returns HTTPResponse.Status
func (r ListAdminsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListAdminsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateAdminResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Admin
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r CreateAdminResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateAdminResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteAdminResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r DeleteAdminResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAdminResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAdminResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Admin
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r GetAdminResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAdminResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateAdminResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Admin
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r UpdateAdminResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateAdminResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetProfileResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Admin
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r GetProfileResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProfileResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListCampaignsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CampaignListResponse
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r ListCampaignsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListCampaignsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateCampaignResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Campaign
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r CreateCampaignResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateCampaignResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteCampaignResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r DeleteCampaignResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteCampaignResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCampaignResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data Campaign `json:"data"`
	}
	JSONDefault *Error
}

// Status returns HTTPResponse.Status
func (r GetCampaignResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCampaignResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateCampaignResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Campaign
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r UpdateCampaignResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateCampaignResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DuplicateCampaignResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Campaign
	JSONDefault  *Error
}

// Status returns HTTPResponse.Status
func (r DuplicateCampaignResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DuplicateCampaignResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCampaignUsersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data   []CampaignUser `json:"data"`
		Limit  int            `json:"limit"`
		Offset int            `json:"offset"`
		Total  int            `json:"total"`
	}
	JSONDefault *Error
}

// Status returns HTTPResponse.Status
func (r GetCampaignUsersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCampaignUsersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListAdminsWithResponse request returning *ListAdminsResponse
func (c *ClientWithResponses) ListAdminsWithResponse(ctx context.Context, params *ListAdminsParams, reqEditors ...RequestEditorFn) (*ListAdminsResponse, error) {
	rsp, err := c.ListAdmins(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListAdminsResponse(rsp)
}

// CreateAdminWithBodyWithResponse request with arbitrary body returning *CreateAdminResponse
func (c *ClientWithResponses) CreateAdminWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAdminResponse, error) {
	rsp, err := c.CreateAdminWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAdminResponse(rsp)
}

func (c *ClientWithResponses) CreateAdminWithResponse(ctx context.Context, body CreateAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAdminResponse, error) {
	rsp, err := c.CreateAdmin(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAdminResponse(rsp)
}

// DeleteAdminWithResponse request returning *DeleteAdminResponse
func (c *ClientWithResponses) DeleteAdminWithResponse(ctx context.Context, adminID openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteAdminResponse, error) {
	rsp, err := c.DeleteAdmin(ctx, adminID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAdminResponse(rsp)
}

// GetAdminWithResponse request returning *GetAdminResponse
func (c *ClientWithResponses) GetAdminWithResponse(ctx context.Context, adminID openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetAdminResponse, error) {
	rsp, err := c.GetAdmin(ctx, adminID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAdminResponse(rsp)
}

// UpdateAdminWithBodyWithResponse request with arbitrary body returning *UpdateAdminResponse
func (c *ClientWithResponses) UpdateAdminWithBodyWithResponse(ctx context.Context, adminID openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateAdminResponse, error) {
	rsp, err := c.UpdateAdminWithBody(ctx, adminID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateAdminResponse(rsp)
}

func (c *ClientWithResponses) UpdateAdminWithResponse(ctx context.Context, adminID openapi_types.UUID, body UpdateAdminJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateAdminResponse, error) {
	rsp, err := c.UpdateAdmin(ctx, adminID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateAdminResponse(rsp)
}

// GetProfileWithResponse request returning *GetProfileResponse
func (c *ClientWithResponses) GetProfileWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetProfileResponse, error) {
	rsp, err := c.GetProfile(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProfileResponse(rsp)
}

// ListCampaignsWithResponse request returning *ListCampaignsResponse
func (c *ClientWithResponses) ListCampaignsWithResponse(ctx context.Context, projectID openapi_types.UUID, params *ListCampaignsParams, reqEditors ...RequestEditorFn) (*ListCampaignsResponse, error) {
	rsp, err := c.ListCampaigns(ctx, projectID, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListCampaignsResponse(rsp)
}

// CreateCampaignWithBodyWithResponse request with arbitrary body returning *CreateCampaignResponse
func (c *ClientWithResponses) CreateCampaignWithBodyWithResponse(ctx context.Context, projectID openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateCampaignResponse, error) {
	rsp, err := c.CreateCampaignWithBody(ctx, projectID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateCampaignResponse(rsp)
}

func (c *ClientWithResponses) CreateCampaignWithResponse(ctx context.Context, projectID openapi_types.UUID, body CreateCampaignJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateCampaignResponse, error) {
	rsp, err := c.CreateCampaign(ctx, projectID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateCampaignResponse(rsp)
}

// DeleteCampaignWithResponse request returning *DeleteCampaignResponse
func (c *ClientWithResponses) DeleteCampaignWithResponse(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteCampaignResponse, error) {
	rsp, err := c.DeleteCampaign(ctx, projectID, campaignID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteCampaignResponse(rsp)
}

// GetCampaignWithResponse request returning *GetCampaignResponse
func (c *ClientWithResponses) GetCampaignWithResponse(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetCampaignResponse, error) {
	rsp, err := c.GetCampaign(ctx, projectID, campaignID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCampaignResponse(rsp)
}

// UpdateCampaignWithBodyWithResponse request with arbitrary body returning *UpdateCampaignResponse
func (c *ClientWithResponses) UpdateCampaignWithBodyWithResponse(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateCampaignResponse, error) {
	rsp, err := c.UpdateCampaignWithBody(ctx, projectID, campaignID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateCampaignResponse(rsp)
}

func (c *ClientWithResponses) UpdateCampaignWithResponse(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, body UpdateCampaignJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateCampaignResponse, error) {
	rsp, err := c.UpdateCampaign(ctx, projectID, campaignID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateCampaignResponse(rsp)
}

// DuplicateCampaignWithResponse request returning *DuplicateCampaignResponse
func (c *ClientWithResponses) DuplicateCampaignWithResponse(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, reqEditors ...RequestEditorFn) (*DuplicateCampaignResponse, error) {
	rsp, err := c.DuplicateCampaign(ctx, projectID, campaignID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDuplicateCampaignResponse(rsp)
}

// GetCampaignUsersWithResponse request returning *GetCampaignUsersResponse
func (c *ClientWithResponses) GetCampaignUsersWithResponse(ctx context.Context, projectID openapi_types.UUID, campaignID openapi_types.UUID, params *GetCampaignUsersParams, reqEditors ...RequestEditorFn) (*GetCampaignUsersResponse, error) {
	rsp, err := c.GetCampaignUsers(ctx, projectID, campaignID, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCampaignUsersResponse(rsp)
}

// ParseListAdminsResponse parses an HTTP response from a ListAdminsWithResponse call
func ParseListAdminsResponse(rsp *http.Response) (*ListAdminsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListAdminsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Limit Maximum number of items returned
			Limit int `json:"limit"`

			// Offset Number of items skipped
			Offset  int     `json:"offset"`
			Results []Admin `json:"results"`

			// Total Total number of items matching the filters
			Total int `json:"total"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCreateAdminResponse parses an HTTP response from a CreateAdminWithResponse call
func ParseCreateAdminResponse(rsp *http.Response) (*CreateAdminResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateAdminResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Admin
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteAdminResponse parses an HTTP response from a DeleteAdminWithResponse call
func ParseDeleteAdminResponse(rsp *http.Response) (*DeleteAdminResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteAdminResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetAdminResponse parses an HTTP response from a GetAdminWithResponse call
func ParseGetAdminResponse(rsp *http.Response) (*GetAdminResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAdminResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Admin
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseUpdateAdminResponse parses an HTTP response from a UpdateAdminWithResponse call
func ParseUpdateAdminResponse(rsp *http.Response) (*UpdateAdminResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateAdminResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Admin
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetProfileResponse parses an HTTP response from a GetProfileWithResponse call
func ParseGetProfileResponse(rsp *http.Response) (*GetProfileResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProfileResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Admin
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseListCampaignsResponse parses an HTTP response from a ListCampaignsWithResponse call
func ParseListCampaignsResponse(rsp *http.Response) (*ListCampaignsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListCampaignsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CampaignListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCreateCampaignResponse parses an HTTP response from a CreateCampaignWithResponse call
func ParseCreateCampaignResponse(rsp *http.Response) (*CreateCampaignResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateCampaignResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Campaign
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteCampaignResponse parses an HTTP response from a DeleteCampaignWithResponse call
func ParseDeleteCampaignResponse(rsp *http.Response) (*DeleteCampaignResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteCampaignResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetCampaignResponse parses an HTTP response from a GetCampaignWithResponse call
func ParseGetCampaignResponse(rsp *http.Response) (*GetCampaignResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCampaignResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data Campaign `json:"data"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseUpdateCampaignResponse parses an HTTP response from a UpdateCampaignWithResponse call
func ParseUpdateCampaignResponse(rsp *http.Response) (*UpdateCampaignResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateCampaignResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Campaign
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDuplicateCampaignResponse parses an HTTP response from a DuplicateCampaignWithResponse call
func ParseDuplicateCampaignResponse(rsp *http.Response) (*DuplicateCampaignResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DuplicateCampaignResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Campaign
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetCampaignUsersResponse parses an HTTP response from a GetCampaignUsersWithResponse call
func ParseGetCampaignUsersResponse(rsp *http.Response) (*GetCampaignUsersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCampaignUsersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data   []CampaignUser `json:"data"`
			Limit  int            `json:"limit"`
			Offset int            `json:"offset"`
			Total  int            `json:"total"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List organization admins
	// (GET /api/admin/organizations/admins)
	ListAdmins(w http.ResponseWriter, r *http.Request, params ListAdminsParams)
	// Create or update admin
	// (POST /api/admin/organizations/admins)
	CreateAdmin(w http.ResponseWriter, r *http.Request)
	// Delete admin
	// (DELETE /api/admin/organizations/admins/{adminID})
	DeleteAdmin(w http.ResponseWriter, r *http.Request, adminID openapi_types.UUID)
	// Get admin by ID
	// (GET /api/admin/organizations/admins/{adminID})
	GetAdmin(w http.ResponseWriter, r *http.Request, adminID openapi_types.UUID)
	// Update admin
	// (PATCH /api/admin/organizations/admins/{adminID})
	UpdateAdmin(w http.ResponseWriter, r *http.Request, adminID openapi_types.UUID)
	// Get current admin profile
	// (GET /api/admin/profile)
	GetProfile(w http.ResponseWriter, r *http.Request)
	// List campaigns
	// (GET /api/admin/projects/{projectID}/campaigns)
	ListCampaigns(w http.ResponseWriter, r *http.Request, projectID openapi_types.UUID, params ListCampaignsParams)
	// Create campaign
	// (POST /api/admin/projects/{projectID}/campaigns)
	CreateCampaign(w http.ResponseWriter, r *http.Request, projectID openapi_types.UUID)
	// Delete campaign
	// (DELETE /api/admin/projects/{projectID}/campaigns/{campaignID})
	DeleteCampaign(w http.ResponseWriter, r *http.Request, projectID openapi_types.UUID, campaignID openapi_types.UUID)
	// Get campaign by ID
	// (GET /api/admin/projects/{projectID}/campaigns/{campaignID})
	GetCampaign(w http.ResponseWriter, r *http.Request, projectID openapi_types.UUID, campaignID openapi_types.UUID)
	// Update campaign
	// (PATCH /api/admin/projects/{projectID}/campaigns/{campaignID})
	UpdateCampaign(w http.ResponseWriter, r *http.Request, projectID openapi_types.UUID, campaignID openapi_types.UUID)
	// Duplicate campaign
	// (POST /api/admin/projects/{projectID}/campaigns/{campaignID}/duplicate)
	DuplicateCampaign(w http.ResponseWriter, r *http.Request, projectID openapi_types.UUID, campaignID openapi_types.UUID)
	// Get campaign users
	// (GET /api/admin/projects/{projectID}/campaigns/{campaignID}/users)
	GetCampaignUsers(w http.ResponseWriter, r *http.Request, projectID openapi_types.UUID, campaignID openapi_types.UUID, params GetCampaignUsersParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List organization admins
// (GET /api/admin/organizations/admins)
func (_ Unimplemented) ListAdmins(w http.ResponseWriter, r *http.Request, params ListAdminsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create or update admin
// (POST /api/admin/organizations/admins)
func (_ Unimplemented) CreateAdmin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete admin
// (DELETE /api/admin/organizations/admins/{adminID})
func (_ Unimplemented) DeleteAdmin(w http.ResponseWriter, r *http.Request, adminID openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get admin by ID
// (GET /api/admin/organizations/admins/{adminID})
func (_ Unimplemented) GetAdmin(w http.ResponseWriter, r *http.Request, adminID openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update admin
// (PATCH /api/admin/organizations/admins/{adminID})
func (_ Unimplemented) UpdateAdmin(w http.ResponseWriter, r *http.Request, adminID openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current admin profile
// (GET /api/admin/profile)
func (_ Unimplemented) GetProfile(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List campaigns
// (GET /api/admin/projects/{projectID}/campaigns)
func (_ Unimplemented) ListCampaigns(w http.ResponseWriter, r *http.Request, projectID openapi_types.UUID, params ListCampaignsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create campaign
// (POST /api/admin/projects/{projectID}/campaigns)
func (_ Unimplemented) CreateCampaign(w http.ResponseWriter, r *http.Request, projectID openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete campaign
// (DELETE /api/admin/projects/{projectID}/campaigns/{campaignID})
func (_ Unimplemented) DeleteCampaign(w http.ResponseWriter, r *http.Request, projectID openapi_types.UUID, campaignID openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get campaign by ID
// (GET /api/admin/projects/{projectID}/campaigns/{campaignID})
func (_ Unimplemented) GetCampaign(w http.ResponseWriter, r *http.Request, projectID openapi_types.UUID, campaignID openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update campaign
// (PATCH /api/admin/projects/{projectID}/campaigns/{campaignID})
func (_ Unimplemented) UpdateCampaign(w http.ResponseWriter, r *http.Request, projectID openapi_types.UUID, campaignID openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Duplicate campaign
// (POST /api/admin/projects/{projectID}/campaigns/{campaignID}/duplicate)
func (_ Unimplemented) DuplicateCampaign(w http.ResponseWriter, r *http.Request, projectID openapi_types.UUID, campaignID openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get campaign users
// (GET /api/admin/projects/{projectID}/campaigns/{campaignID}/users)
func (_ Unimplemented) GetCampaignUsers(w http.ResponseWriter, r *http.Request, projectID openapi_types.UUID, campaignID openapi_types.UUID, params GetCampaignUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAdmins operation middleware
func (siw *ServerInterfaceWrapper) ListAdmins(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, HttpBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAdminsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "search" -------------

	err = runtime.BindQueryParameter("form", true, false, "search", r.URL.Query(), &params.Search)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "search", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAdmins(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAdmin operation middleware
func (siw *ServerInterfaceWrapper) CreateAdmin(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, HttpBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAdmin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAdmin operation middleware
func (siw *ServerInterfaceWrapper) DeleteAdmin(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "adminID" -------------
	var adminID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "adminID", chi.URLParam(r, "adminID"), &adminID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "adminID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, HttpBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAdmin(w, r, adminID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdmin operation middleware
func (siw *ServerInterfaceWrapper) GetAdmin(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "adminID" -------------
	var adminID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "adminID", chi.URLParam(r, "adminID"), &adminID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "adminID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, HttpBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdmin(w, r, adminID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAdmin operation middleware
func (siw *ServerInterfaceWrapper) UpdateAdmin(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "adminID" -------------
	var adminID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "adminID", chi.URLParam(r, "adminID"), &adminID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "adminID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, HttpBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAdmin(w, r, adminID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProfile operation middleware
func (siw *ServerInterfaceWrapper) GetProfile(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, HttpBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProfile(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCampaigns operation middleware
func (siw *ServerInterfaceWrapper) ListCampaigns(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectID" -------------
	var projectID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", chi.URLParam(r, "projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, HttpBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCampaignsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCampaigns(w, r, projectID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCampaign operation middleware
func (siw *ServerInterfaceWrapper) CreateCampaign(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectID" -------------
	var projectID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", chi.URLParam(r, "projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, HttpBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCampaign(w, r, projectID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCampaign operation middleware
func (siw *ServerInterfaceWrapper) DeleteCampaign(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectID" -------------
	var projectID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", chi.URLParam(r, "projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectID", Err: err})
		return
	}

	// ------------- Path parameter "campaignID" -------------
	var campaignID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "campaignID", chi.URLParam(r, "campaignID"), &campaignID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "campaignID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, HttpBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCampaign(w, r, projectID, campaignID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCampaign operation middleware
func (siw *ServerInterfaceWrapper) GetCampaign(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectID" -------------
	var projectID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", chi.URLParam(r, "projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectID", Err: err})
		return
	}

	// ------------- Path parameter "campaignID" -------------
	var campaignID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "campaignID", chi.URLParam(r, "campaignID"), &campaignID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "campaignID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, HttpBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCampaign(w, r, projectID, campaignID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCampaign operation middleware
func (siw *ServerInterfaceWrapper) UpdateCampaign(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectID" -------------
	var projectID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", chi.URLParam(r, "projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectID", Err: err})
		return
	}

	// ------------- Path parameter "campaignID" -------------
	var campaignID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "campaignID", chi.URLParam(r, "campaignID"), &campaignID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "campaignID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, HttpBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCampaign(w, r, projectID, campaignID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DuplicateCampaign operation middleware
func (siw *ServerInterfaceWrapper) DuplicateCampaign(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectID" -------------
	var projectID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", chi.URLParam(r, "projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectID", Err: err})
		return
	}

	// ------------- Path parameter "campaignID" -------------
	var campaignID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "campaignID", chi.URLParam(r, "campaignID"), &campaignID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "campaignID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, HttpBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DuplicateCampaign(w, r, projectID, campaignID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCampaignUsers operation middleware
func (siw *ServerInterfaceWrapper) GetCampaignUsers(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectID" -------------
	var projectID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectID", chi.URLParam(r, "projectID"), &projectID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectID", Err: err})
		return
	}

	// ------------- Path parameter "campaignID" -------------
	var campaignID openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "campaignID", chi.URLParam(r, "campaignID"), &campaignID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "campaignID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, HttpBearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCampaignUsersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCampaignUsers(w, r, projectID, campaignID, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/admin/organizations/admins", wrapper.ListAdmins)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/admin/organizations/admins", wrapper.CreateAdmin)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/admin/organizations/admins/{adminID}", wrapper.DeleteAdmin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/admin/organizations/admins/{adminID}", wrapper.GetAdmin)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/admin/organizations/admins/{adminID}", wrapper.UpdateAdmin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/admin/profile", wrapper.GetProfile)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/admin/projects/{projectID}/campaigns", wrapper.ListCampaigns)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/admin/projects/{projectID}/campaigns", wrapper.CreateCampaign)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/admin/projects/{projectID}/campaigns/{campaignID}", wrapper.DeleteCampaign)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/admin/projects/{projectID}/campaigns/{campaignID}", wrapper.GetCampaign)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/admin/projects/{projectID}/campaigns/{campaignID}", wrapper.UpdateCampaign)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/admin/projects/{projectID}/campaigns/{campaignID}/duplicate", wrapper.DuplicateCampaign)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/admin/projects/{projectID}/campaigns/{campaignID}/users", wrapper.GetCampaignUsers)
	})

	return r
}
