/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/webhooks/providers/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bootstrap default integrations for a new project
         * @description Called by Lunogram when a new project is created.
         *     The endpoint should return one or more default providers and/or an `external_id`
         *     that can be used by Lunogram to send or fetch configuration.
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description Unique identifier of the project
                         */
                        project_id: string;
                        /**
                         * Format: uuid
                         * @description Organization to which the project belongs
                         */
                        organization_id?: string;
                    };
                };
            };
            responses: {
                /** @description Default providers and/or external reference */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            providers?: components["schemas"]["Provider"][];
                            /** @description Identifier for the provider or configuration */
                            external_id?: string;
                        };
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server error in external system */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/provider/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a message through an external provider
         * @description Called by Lunogram to send a message through the external provider identified by `external_id`.
         *     The request body can represent an **email**, **SMS**, or **push** notification.
         *
         */
        post: {
            parameters: {
                query: {
                    /** @description External identifier of the provider */
                    external_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Email"] | components["schemas"]["TextMessage"] | components["schemas"]["Push"];
                };
            };
            responses: {
                /** @description Message accepted by the external system */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid payload or unsupported message type */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Provider not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server error in external system */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Provider: {
            /** @description Provider type (e.g., "twilio", "sendgrid", "slack") */
            type: string;
            /** @description Display name of the provider */
            name: string;
            /**
             * @description Group of the provider
             * @enum {string}
             */
            group: "email" | "text" | "push" | "webhook" | "analytics";
            /** @description Provider-specific configuration data */
            data: {
                [key: string]: unknown;
            };
            /** @description Whether this provider is marked as default */
            is_default: boolean;
            /**
             * @description Rate limit interval
             * @enum {string}
             */
            rate_interval?: "second" | "minute" | "hour" | "day";
            /** @description Maximum number of requests allowed in the specified interval */
            rate_limit?: number;
            /** @description External identifier to fetch or send through */
            external_id?: string | null;
        };
        Email: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "email";
            to: string;
            from: string | components["schemas"]["NamedEmail"];
            cc?: string;
            bcc?: string;
            reply_to?: string;
            subject: string;
            text?: string;
            html?: string;
            headers?: {
                [key: string]: unknown;
            };
            list?: {
                unsubscribe?: string;
            };
        };
        TextMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            to: string;
            text: string;
        };
        Push: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "push";
            tokens: string | string[];
            title: string;
            body: string;
            custom?: {
                [key: string]: unknown;
            };
        };
        NamedEmail: {
            name: string;
            email: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
