// Code generated by "stringer -type=WebhookEventName -linecomment"; DO NOT EDIT.

package providers

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventSent-1]
	_ = x[EventDelivered-2]
	_ = x[EventBounced-3]
	_ = x[EventDeferred-4]
	_ = x[EventDropped-5]
	_ = x[EventOpened-6]
	_ = x[EventClicked-7]
	_ = x[EventComplained-8]
	_ = x[EventUnsubscribed-9]
	_ = x[webhookEventNameCount-10]
}

const _WebhookEventName_name = "provider.sentprovider.deliveredprovider.bouncedprovider.deferredprovider.droppedprovider.openedprovider.clickedprovider.complainedprovider.unsubscribedsentinel"

var _WebhookEventName_index = [...]uint8{0, 13, 31, 47, 64, 80, 95, 111, 130, 151, 159}

func (i WebhookEventName) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_WebhookEventName_index)-1 {
		return "WebhookEventName(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WebhookEventName_name[_WebhookEventName_index[idx]:_WebhookEventName_index[idx+1]]
}
